### ISSUE TITLE
How to display frames in loop to animate gif in awe.js

### ISSUE THREAD

**Issue by binita12345** [awe-media/awe.js#50] opened 2017-08-12 10:03 UTC
if i have 6 image frames 
![tmp-0](https://user-images.githubusercontent.com/23699891/29238330-fb8fed3c-7f50-11e7-97e4-340640f23d0b.png)
![tmp-1](https://user-images.githubusercontent.com/23699891/29238331-fb9257d4-7f50-11e7-8b24-525590b01f4b.png)
![tmp-2](https://user-images.githubusercontent.com/23699891/29238332-fb96393a-7f50-11e7-9b22-0efe4c181676.png)
![tmp-3](https://user-images.githubusercontent.com/23699891/29238333-fb9ebcc2-7f50-11e7-8441-0a45137c41d3.png)
![tmp-4](https://user-images.githubusercontent.com/23699891/29238334-fba0083e-7f50-11e7-8093-3f90eaca4d62.png)
![tmp-5](https://user-images.githubusercontent.com/23699891/29238335-fba18466-7f50-11e7-8382-8cb16fdd8551.png)

for  below gif 
![sb-butterfly](https://user-images.githubusercontent.com/23699891/29238326-db34fc4e-7f50-11e7-8c09-819ddad7e50d.gif)

so, how can i set those frames in loop to flapping for butterfly.

Please give me any solution.

**Comment by binita12345** [comment] 2017-08-12 10:30
https://www.opengl.org/discussion_boards/showthread.php/198512-How-make-an-animated-texture-%28OpenGL-DevIL-C-%29

You can't load a single animated texture like this.

What you do is load each frame as a separate texture, then animate it as time passes.

For example, if your .gif had 10 frames, you would load create 10 separate textures and load each frame into each texture. Then, if you wished to animate them at 10 fps, you check the amount of time that has passed. If 0 to 0.1 seconds has passed you display frame 0, if 0.1 to 0.2 seconds has passed you display frame 1, and so on.

Any Demo is available for above solution ?

**Comment by awe-media** [comment] 2017-08-13 05:18
Feel free to provide a pull request if you'd like to submit some code. Otherwise this is not a bug - this is a feature request so closing.

**Closed as completed by awe-media** 2017-08-13 05:18 UTC

**Comment by awe-media** [comment] 2017-08-13 06:30
NOTE: You can also use the `projection.update()` api to update the texture periodically too. e.g.

```
var butterfly = awe.projections.view(PROJECTION_ID_HERE);
var i = 1;
b.update({
  position:{ y:1 }, // use a minimal non-zero update here
  animation:{
    duration:0.2, // 5 animation steps are 1/5th of a second
    repeat:5, // play for 1 second total
    persist:0,
    step_callback:function() { 
      i++; if (i>5) { i = 1; } // add time scaling here if the animation is too fast
      b.update({ texture:{ path:i+'.png' } });
    }
  }
});
```

**Comment by binita12345** [comment] 2017-08-14 12:39
thanks for your reply
but i have to trigger update function periodically in my app, 
how is it possible? how to trigger that function periodically?
if you have any solution, give me soon reply.
