### ISSUE TITLE
How load .obj texture properly

### ISSUE THREAD

**Issue by m1gu** [awe-media/awe.js#10] opened 2016-12-05 22:10 UTC
I try load a .obj with UV texture with this code.
awe.projections.add({ 
	id:'marker_projection', 
	geometry: { path: 'carro.obj' },
        position: { x:0, y:0, z:0 },
        rotation: { x:0, y:0, z:0 },
        scale: { x:0.3, y:0.3, z:0.3 },
	material:{ path: 'carro.mtl' },
        visible: false,
}, { poi_id: 'jsartoolkit_marker_64' });

But in the AR show all in black.
This is my test link
https://comunadigital.com.ec/awemiguel/

Best regards,

**Comment by awe-media** [comment] 2016-12-06 00:05
Hi @m1gu - this is really an `.mtl` formatting issue not really an `awe.js` issue. If you upload this object to an https://awe.media account you'll find that we automatically fix these types of things up for you.

Most likely the issue is that you have a hardcoded path to your texture file in your `.mtl`.

See:
```
map_Kd C:RESPALDO MIGUEL/Comuna Digital/Proyectos/Valvoline/Realidad Aumentada/carrora OLD/resources/tex.jpg
```

The texture file seems available at the same level so you should just shorten that to:
```
map_Kd tex.jpg
```

You probably want to tune your `Ka` and `Ks` values too - but that depends on what you want it to look like.

Hope that helps and we'll close this issue now.

**Closed as completed by awe-media** 2016-12-06 00:05 UTC
